config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new', as: :new
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit
  patch 'tasks/:id', to: 'tasks#update', as: :update

  get 'tasks/:id', to: 'tasks#show', as: :task

  delete 'tasks/:id', to: 'tasks#delete'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :delete]
  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    index
    render :index
  end

  def edit
  end

  def update
    @task.update(task_params)
    index
    render :show
  end

  def delete
    @task.destroy
    index
    render :index
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.0.7/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |t| %>
  <div class="form-group">
    <%= t.label :title %>
    <%= t.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= t.label :details %>
    <%= t.text_field :details, class: 'form-control' %>
  </div>

  <%= t.submit class: 'btn btn-primary' %>
<% end %>

<p><%= link_to "back to all tasks", tasks_path %></p>

app/views/tasks/edit.html.erb
<%= render 'form', task: @task %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>
<% @tasks.each do |task| %>
<ul><input type="checkbox">
  <%= link_to task.title, task_path(task) %>
  <%= link_to  task_path(task),
      method: :delete,
      data: { confirm: "Do you want to delete #{task.title}?" } do %>
      <i class="far fa-trash-alt"></i>
      <% end %>
</ul>
<% end %>

<%= link_to new_path do %>
  <i class="fas fa-plus"></i> add a new task
<% end %>

app/views/tasks/new.html.erb
<%= render 'form', task: @task %>

app/views/tasks/show.html.erb
<div class="d-flex">
  <h1><%= @task.title %></h1>
  <%= link_to "edit this task", edit_path, class: 'align-self-end btn btn-primary' %>
</div>
<div class="alert alert-secondary">
  <p><%= @task.details %></p>
</div>

<input type="checkbox"> <%= @task.completed == false ? "Not completed" : "Completed" %>

<%= link_to "back to all tasks", tasks_path %></p>